name: "jg1-integrations-deploy"
on:
  push:
jobs:
  deploy:
    name: Deploy to PROD
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Composer action
        uses: php-actions/composer@v1
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        with:
          configuration: test/phpunit.xml
          args: --coverage-text
      - name: List vendor folder
        run: |
          ls -ld ${{github.workspace}}/vendor
      - name: Delete vendor folder
        run: |
          ls -ld ${{github.workspace}}/vendor
          sudo rm -rf ${{github.workspace}}/vendor
      - name: Run deploy dev
        uses: pagely/action-deploy@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs"
          PAGELY_INTEGRATION_SECRET: ${{secrets.JG1_INTEGRATIONS_SECRET}}
          PAGELY_INTEGRATION_ID: "YeLQLiB6M7yMCehkiM7J75"
          PAGELY_APP_ID: "35297"
          PAGELY_WORKING_DIR: ${{github.workspace}}
      - name: Run deploy prod
        uses: pagely/action-deploy@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs"
          PAGELY_INTEGRATION_SECRET: ${{secrets.JG1_INTEGRATIONS_SECRET}}
          PAGELY_INTEGRATION_ID: "YeLQLiB6M7yMCehkiM7J75"
          PAGELY_APP_ID: "35295"
          PAGELY_WORKING_DIR: ${{github.workspace}}
